[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=6144"
GENERATE_SOURCEMAP = "false"
CI = "false"
NPM_CONFIG_TIMEOUT = "300000"

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "echo 'Installing dependencies...'",
  "npm install --legacy-peer-deps --no-audit --no-fund",
  "echo 'Dependencies installed successfully'"
]

[phases.build]
cmds = [
  "echo 'Starting React build process...'",
  "npm run build",
  "echo 'React build completed successfully'",
  "npm install -g serve"
]

[start]
cmd = "node server.js"