[build]
builder = "DOCKERFILE"
buildCommand = ""

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
REACT_APP_API_URL = "https://kind-benevolence-production.up.railway.app/api"
REACT_APP_SOCKET_URL = "https://kind-benevolence-production.up.railway.app"
CI = "false"
GENERATE_SOURCEMAP = "false"
TSC_COMPILE_ON_ERROR = "true"
SKIP_PREFLIGHT_CHECK = "true"
